[colors]
ansi = [
	 '#3B4252', # black
	 '#BF616A', # red
	 '#8FBCBB', # green
	 '#EBCB8B', # yellow
	 '#81A1C1', # blue
	 '#5E81AC', # purple
	 '#88C0D0', # cyan
	 '#757e90', # white
]
brights = [
	 '#434C5E', # black
	 '#d3757e', # red
	 '#a3d0cf', # green
	 '#ffdf9f', # yellow
	 '#95b5d5', # blue
	 '#B48EAD', # purple
	 '#9cd4e4', # cyan
	 '#ECEFF4', # white
]

background = '#2E3440'
foreground = '#E5E9F0'

cursor_bg = '#E5E9F0'
cursor_border  = '#E5E9F0'
cursor_fg = '#2E3440'

selection_bg = '#81A1C1'
selection_fg = '#2E3440'

[colors.indexed]

[metadata]
name = 'arctic' 
