[colors]
ansi = [
	 '#687781', # black
	 '#9d5060', # red
	 '#49a078', # green
	 '#d7ba89', # yellow
	 '#90b0ff', # blue
	 '#bf79bf', # purple
	 '#a1cca5', # cyan
	 '#bec4de', # white
]
brights = [
	 '#8c92ac', # black
	 '#b16474', # red
	 '#5db48c', # green
	 '#ebce9d', # yellow
	 '#a4c4ff', # blue
	 '#bf40bf', # purple
	 '#b5e0b9', # cyan
	 '#e5dada', # white
]

background = '#030027'
foreground = '#bec4de'

cursor_bg = '#bec4de'
cursor_border  = '#bec4de'
cursor_fg = '#030027'

selection_bg = '#36454f'
selection_fg = '#bec4de'

[colors.indexed]

[metadata]
name = 'deep_purple' 
