[colors]
ansi = [
	 '#624d4e', # black
	 '#ff5051', # red
	 '#9ee865', # green
	 '#f5de69', # yellow
	 '#899eea', # blue
	 '#b969f3', # purple
	 '#66d8f6', # cyan
	 '#d1d3d1', # white
]
brights = [
	 '#9fa19f', # black
	 '#ff6465', # red
	 '#b2fc79', # green
	 '#fff27d', # yellow
	 '#9db2fe', # blue
	 '#e46cca', # purple
	 '#7aecff', # cyan
	 '#e5f1ec', # white
]

background = '#232d36'
foreground = '#d1e5d9'

cursor_bg = '#d1e5d9'
cursor_border  = '#d1e5d9'
cursor_fg = '#232d36'

selection_bg = '#899eea'
selection_fg = '#232d36'

[colors.indexed]

[metadata]
name = 'pokemon' 
